name: Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Deps
        run: sudo apt -y update && sudo apt -y install git curl cmake build-essential

      - name: Install vcpkg
        run: git clone https://github.com/microsoft/vcpkg.git && cd vcpkg && ./bootstrap-vcpkg.sh && export PATH="$PATH:$(pwd)" && export VCPKG_ROOT="$(pwd)"

      - name: Run vcpkg install
        run: vcpkg install

      - name: Configure CMake
        run: CMAKE_TOOLCHAIN_FILE="`find $VCPKG_ROOT -name vcpkg.cmake`" && cmake -S . -B bin/ -DBUILD_TEST=true -DCMAKE_TOOLCHAIN_FILE=$CMAKE_TOOLCHAIN_FILE

      - name: Build sources
        run: cmake --build bin/ --parallel 4
